name: app
services:
  code:
    public: true
    build: code
    replicas: 5
    ports:
      - 5000
      - 3000
      - 3001
    resources:
      cpu: 1000m
      memory: 3Gi
      storage: 5Gi
    entrypoint: /developer/bin/start-shell