name: app
services:
  code:
    public: true
    build: code
    replicas: 2
    ports:
      - 5000
      - 3000
      - 3001
    resources:
      cpu: 3500m
      memory: 7064Gi
      storage: 3Gi
    volumes: 
      ["/developer/.config/Code",
      "/developer/.vscode",
      "/developer/.ssh",
      "/developer/project"]
    entrypoint: /developer/bin/start-shell